definitions:
  block.BlockChain:
    type: object
  controllers.MessageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /blockchain:
    post:
      consumes:
      - application/json
      description: Create new blockchain on the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/block.BlockChain'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.MessageResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Blockchain By Port Service
      tags:
      - blockchain
swagger: "2.0"
